const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Behaviors.Orbit,
		C3.Behaviors.Turret,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{Твёрдый: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Аудио: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{text: 0},
	{СквознаяПлатформа: 0},
	{Спрайт8: 0},
	{Текст: 0},
	{Спрайт9: 0},
	{Синусоида: 0},
	{Спрайт10: 0},
	{Key: 0},
	{Спрайт11: 0},
	{Текст2: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{Спрайт: 0},
	{Орбита: 0},
	{Спрайт14: 0},
	{Турель: 0},
	{Спрайт15: 0},
	{Пуля: 0},
	{Спрайт16: 0},
	{Частицы2: 0},
	{Спрайт17: 0},
	{Спрайт18: 0},
	{Угасание: 0},
	{Спрайт19: 0},
	{Спрайт20: 0},
	{Спрайт21: 0},
	{Спрайт22: 0},
	{Мышь: 0},
	{play: 0},
	{EXIT: 0},
	{Текст3: 0},
	{Текст4: 0},
	{Спрайт25: 0},
	{finish: 0},
	{Спрайт23: 0},
	{Спрайт24: 0},
	{Спрайт26: 0},
	{coin: 0}
];

self.InstanceType = {
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	text: class extends self.ITextInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	Спрайт22: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	play: class extends self.ISpriteInstance {},
	EXIT: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	Текст4: class extends self.ITextInstance {},
	Спрайт25: class extends self.ISpriteInstance {},
	finish: class extends self.ITextInstance {},
	Спрайт23: class extends self.ISpriteInstance {},
	Спрайт24: class extends self.ISpriteInstance {},
	Спрайт26: class extends self.ISpriteInstance {},
	coin: class extends self.ITextInstance {}
}